spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git

  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config" # resources package ichidagilar uchun
#          search-locations: "file:///Users//eazybank//Document//config" # linux uchun. yani linux dagi biror package ning ichida config filelarni saqlab ishlatish
#          search-locations: "file:///C://config" # windows uchun. yani windows dagi biror package ning ichida config filelarni saqlab ishlatish
        git:
          uri: "https://github.com/TokhirAsadov/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  #  /actuator/busrefresh
  #  config serverga bog'lanish uchun
  #  rabbit mq ga bog`langan barcha microservice larni
  #  refresh qilish uchun ishlatiladi
  #  bunda microservice dagi istalgan server ning /actuator/busrefresh API ga POST request yuboriladi
  #  va barcha microservice lar config filelari automatik yangilanadi
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# bu yerda management endpointslarini ochib beramiz
# yani config serverga kirish uchun
# config server dagi o`zgarishlarni refresh qilish uchun
management:
  endpoints:
    web:
      exposure:
        include: "*" #  8080/actuator/refresh - POST

# health checklar uchun
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


encrypt:
  key: "45D5E6F7G8H9I05O6P7Q8R9S2V3W8B9C0D1EI6J7K8L9M"

server:
  port: 8071