spring:
  application:
    name: eurekaserver

  config:
    import: "optional:configserver:http://localhost:8071/"

# bu yerda management endpointslarini ochib beramiz
# yani config serverga kirish uchun
# config server dagi o`zgarishlarni refresh qilish uchun
management:
  endpoints:
    web:
      exposure:
        include: "*" #  8080/actuator/refresh - POST

  # health checklar uchun
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
