services:
  accountsdb:
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yaml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yaml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yaml
      service: microservice-db-config

  configserver:
    image: registry.hub.docker.com/guvalakat/configserver:s3
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy

#   health checklar uchun
#   readiness-state: servis tayyorligini tekshiradi
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s     # 10 soniyada bir marta tekshiradi
      timeout: 5s       # 5 soniyada javob qaytarishi kerak
      retries: 3        # 3 marta tekshiradi
      start_period: 10s # 10 soniyadan keyin tekshira boshlaydi
    extends:
      file: common-config.yaml
      service: microservice-base-config

  accounts:
    image: registry.hub.docker.com/guvalakat/accounts:s3
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    depends_on:
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config


  loans:
    image: registry.hub.docker.com/guvalakat/loans:s3
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3307/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  cards:
    image: registry.hub.docker.com/guvalakat/cards:s3
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3308/cardsdb"
    depends_on:
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

networks:
  javatuz:
    driver: bridge
