services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ server port
      - "15672:15672" # RabbitMQ management UI port
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s     # 10 soniyada bir marta tekshiradi
      timeout: 5s       # 5 soniyada javob qaytarishi kerak
      retries: 3        # 3 marta tekshiradi
      start_period: 10s # 10 soniyadan keyin tekshira boshlaydi
    extends:
      file: common-config.yaml
      service: network-deploy-service

  configserver:
    image: registry.hub.docker.com/guvalakat/configserver:s3
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy

#   health checklar uchun
#   readiness-state: servis tayyorligini tekshiradi
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s     # 10 soniyada bir marta tekshiradi
      timeout: 5s       # 5 soniyada javob qaytarishi kerak
      retries: 3        # 3 marta tekshiradi
      start_period: 10s # 10 soniyadan keyin tekshira boshlaydi
    extends:
      file: common-config.yaml
      service: microservice-base-config

  accounts:
    image: registry.hub.docker.com/guvalakat/accounts:s3
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config


  loans:
    image: registry.hub.docker.com/guvalakat/loans:s3
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  cards:
    image: registry.hub.docker.com/guvalakat/cards:s3
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

networks:
  javatuz:
    driver: bridge
