server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/"

# bu yerda management endpointslarini ochib beramiz
# yani config serverga kirish uchun
# config server dagi o`zgarishlarni refresh qilish uchun
management:
  endpoints:
    web:
      exposure:
        include: "*" #  8090/actuator/refresh - POST

# health checklar uchun
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true