build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Aliyev Vali - QA Engineer"
    email: "guvalakat1603@gmail.com"
  onCallSupport:
    - (99)336-1603
    - (95)236-0555