services:
  configserver:
    image: registry.hub.docker.com/guvalakat/configserver:s8
    container_name: configserver-ms
    ports:
      - "8071:8071"
#   health checklar uchun
#   readiness-state: servis tayyorligini tekshiradi
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s     # 10 soniyada bir marta tekshiradi
      timeout: 5s       # 5 soniyada javob qaytarishi kerak
      retries: 3        # 3 marta tekshiradi
      start_period: 10s # 10 soniyadan keyin tekshira boshlaydi
    extends:
      file: common-config.yaml
      service: microservice-base-config

  eurekaserver:
    image: registry.hub.docker.com/guvalakat/eurekaserver:s8
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
#   health checklar uchun
#   readiness-state: servis tayyorligini tekshiradi
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s     # 10 soniyada bir marta tekshiradi
      timeout: 5s       # 5 soniyada javob qaytarishi kerak
      retries: 3        # 3 marta tekshiradi
      start_period: 10s # 10 soniyadan keyin tekshira boshlaydi
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"


  accounts:
    image: registry.hub.docker.com/guvalakat/accounts:s8
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config


  loans:
    image: registry.hub.docker.com/guvalakat/loans:s8
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  loans1:
    image: registry.hub.docker.com/guvalakat/loans:s8
    container_name: loans-ms1
    ports:
      - "8091:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  cards:
    image: registry.hub.docker.com/guvalakat/cards:s8
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

networks:
  javatuz:
    driver: bridge
