build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "Tokhir Asadov - Developer"
    email: "guvalakat1603@gmail.com"
  onCallSupport:
    - (99)336-1603
    - (95)236-0555